fix the github workflow

diff --git a/Scripts/BuildEcosystemPackages b/Scripts/BuildEcosystemPackages
--- a/Scripts/BuildEcosystemPackages
+++ b/Scripts/BuildEcosystemPackages
@@ -1,33 +1,38 @@
 #!/bin/bash
-set -e
+set -euo pipefail
 
 swift --version
+if ! command -v ssgc > /dev/null; then
+    echo 'no ssgc command found, aborting'
+    echo 'hint: run script with PATH="${PATH:+${PATH}:}.build/release"'
+    exit 1
+fi
 
 ssgc slave https://github.com/apple/swift-atomics.git 1.2.0 \
-    -u $SWIFT_INSTALLATION \
+    -u "$SWIFT_INSTALLATION" \
     -o TestPackages/swift-atomics.bson
 
 ssgc slave https://github.com/apple/swift-nio.git 2.94.0 \
-    -u $SWIFT_INSTALLATION \
+    -u "$SWIFT_INSTALLATION" \
     -o TestPackages/swift-nio.bson
 
 ssgc slave https://github.com/apple/swift-nio-ssl.git 2.36.0 \
-    -u $SWIFT_INSTALLATION \
+    -u "$SWIFT_INSTALLATION" \
     -o TestPackages/swift-nio-ssl.bson
 
 ssgc slave https://github.com/apple/swift-async-dns-resolver.git 0.1.2 \
-    -u $SWIFT_INSTALLATION \
+    -u "$SWIFT_INSTALLATION" \
     -o TestPackages/swift-async-dns-resolver.bson
 
 ssgc slave https://github.com/swiftlang/swift-syntax.git 603.0.0 \
-    -u $SWIFT_INSTALLATION \
+    -u "$SWIFT_INSTALLATION" \
     -o TestPackages/swift-syntax.bson
 
 ssgc slave https://github.com/swiftlang/indexstore-db.git swift-6.3-RELEASE \
-    -u $SWIFT_INSTALLATION \
+    -u "$SWIFT_INSTALLATION" \
     -o TestPackages/indexstore-db.bson
 
 ssgc slave https://github.com/swiftlang/swift-book.git swift-5.10-fcs \
-    -u $SWIFT_INSTALLATION \
+    -u "$SWIFT_INSTALLATION" \
     -b book \
     -o TestPackages/swift-book.bson
diff --git a/Scripts/BuildLocalTestPackages b/Scripts/BuildLocalTestPackages
--- a/Scripts/BuildLocalTestPackages
+++ b/Scripts/BuildLocalTestPackages
@@ -6,27 +6,23 @@ swift --version
 swift build --package-path TestModules
 swift package --package-path TestModules dump-package > TestModules/Package.swift.json
 
-for output in SymbolGraphs Determinism
-do
-    mkdir -p TestModules/$output
-    for module in Swift _Concurrency _Differentiation
-    do
+for output in SymbolGraphs Determinism; do
+    mkdir -p "TestModules/${output}"
+    for module in Swift _Concurrency _Differentiation; do
         swift symbolgraph-extract \
             -target x86_64-unknown-linux-gnu \
             -minimum-access-level internal \
-            -output-dir TestModules/$output \
+            -output-dir "TestModules/${output}" \
             -skip-inherited-docs \
             -emit-extension-block-symbols \
             -include-spi-symbols \
             -pretty-print \
-            -module-name $module
+            -module-name "$module"
     done
 done
 
-for include in TestModules/.build/debug/Modules
-do
-    for file in $include/*.swiftmodule
-    do
+for include in TestModules/.build/debug/Modules; do
+    for file in $include/*.swiftmodule; do
         swift symbolgraph-extract \
             -target x86_64-unknown-linux-gnu \
             -minimum-access-level internal \
@@ -41,7 +37,13 @@ do
     done
 done
 
-.build/release/ssgc build -u $SWIFT_INSTALLATION \
+if ! command -v ssgc > /dev/null; then
+    echo 'no ssgc command found, aborting'
+    echo 'hint: run script with PATH="${PATH:+${PATH}:}.build/release"'
+    exit 1
+fi
+
+ssgc build -u "$SWIFT_INSTALLATION" \
     -n swift \
     -o TestPackages/swift.bson
 
@@ -55,8 +57,8 @@ packages=(
     cross-module-articles
 )
 
-for PACKAGE in "${packages[@]}"; do
-    .build/release/ssgc build -u $SWIFT_INSTALLATION \
-        -p TestPackages/$PACKAGE \
-        -o TestPackages/$PACKAGE.bson
+for package in "${packages[@]}"; do
+    ssgc build -u "$SWIFT_INSTALLATION" \
+        -p "TestPackages/${package}" \
+        -o "TestPackages/${package}.bson"
 done
